# Usa localhost si lanzas el comando desde VS Code (Windows)
spring.datasource.url=jdbc:mysql://localhost:3306/backpack_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=user
spring.datasource.password=password

# Forzamos a Hibernate a limpiar el pasado
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

